### ISSUE TITLE
The nuget package is not compatible with .Net Core 2.1

### ISSUE THREAD

**Issue by mvanhorne** [emailplatform/ApiParser_csharp#3]
I think it may just be a copy and paste error .... Visual Studio says:
Package ApiParser 1.1.8 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package ApiParser 1.1.8 supports: emailplatform (eMailPlatform,Version=v0.0)

Most of the other packages support a platform like .Net framework or .Net Core. We are writing an integration to email platform on AWS lambda and it uses .net core. Let me know if you have any questions. 

Repro:
1. Create a ASP.net Core Web API solution
2. Add the latest ApiParser Nuget

Expected: Library would be added
Actual:
Recieve error:
Package ApiParser 1.1.11 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package ApiParser 1.1.11 supports: emailplatform (eMailPlatform,Version=v0.0)

**Comment by TheMoogster** [comment]
Is there any update on this one?

**Comment by mvanhorne** [comment]
1.1.11.2 version fixes this issue
